using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using GUIApplication.ServiceReference;
using System.Text.RegularExpressions;

namespace GUIApplication
{
    /// <summary>
    /// Interaction logic for BuyerFinishWindow.xaml
    /// </summary>
    public partial class BuyerFinishWindow : Window
    {
        static IService iServ = new ServiceClient();
        private Buyer buyer;
        private BuyerPrefsWindow buyerWindow;
        private CreateSeller createWindow;
        public BuyerFinishWindow(Buyer b, CreateSeller cs, BuyerPrefsWindow w)
        {
            buyer = b;
            buyerWindow = w;
            createWindow = cs;
            InitializeComponent();
        }

        private void BtnSaveAndClose(object sender, RoutedEventArgs e)
        {
            if (checkInRKI.IsChecked == true)
            {
                buyer.InRKI = true;
            }
            if (checkBuyerApproved.IsChecked == true)
            {
                buyer.BuyerApproved = true;
                buyer.Bank = txtBank.Text;

                buyer.ApprovedAmount = Convert.ToDouble(txtApprovedAmount.Text);
            }
            if (checkOwner.IsChecked == true)
            {
                buyer.OwnesHouse = true;
            }
            if (checkRents.IsChecked == true)
            {
                buyer.LivesForRent = true;
            }
            iServ.InsertBuyer(buyer);
            createWindow.Close();
            buyerWindow.Close();
            this.Close();
        }

        private void BtnCancel(object sender, RoutedEventArgs e)
        {
            createWindow.Close();
            buyerWindow.Close();
            this.Close();
        }

        private void BtnBack(object sender, RoutedEventArgs e)
        {
            this.Close();
        }

        //GotFocus-event that deletes the autogenerated description in the textboxes, when people focues the textbox
        private void txtApprovedAmount_GotFocus(object sender, RoutedEventArgs e)
        {
            if(txtApprovedAmount.Text == "Beløb")
            {
                txtApprovedAmount.Text = "";
            }
        }

        //LostFocus Method that calls the regularexpression-method for the specific textbox
        private void txtApprovedAmount_LostFocus(object sender, RoutedEventArgs e)
        {
            string amount = txtApprovedAmount.Text;
            RegExDouble(amount);
        }

        //The following method uses a regular expression that checks if a string is of the datatype double(if it includes digets and ",")
        private void RegExDouble(string e)
        {
            Regex regex = new Regex(@"^\d+([\,]?\d+)?$");
            if (!regex.IsMatch(e))
            {
                MessageBox.Show("Textboxen indeholder ugyldig information.\nTextboxen tager imod formatet '111,111'. \nMaks 1 komma!");
            }
        }
    }
}
